apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata: 
      labels: 
        app: flask-app
    spec:
      containers:
        - name: nginx-container
          image: blaiseubanako/web-app-devops-project:V1.
          ports:
          - containerPort: 5000
          - hostPort: 80
