
trigger:
- main

pool:
  vmImage: ubuntu-latest
  parallel: 1

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'az-docker-service-connection'
    repository: 'blaiseubanako/web-app-devops-project'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Azure -resource-Service -Connection'
    azureResourceGroup: 'blaise-devops-rg'
    kubernetesCluster: 'blaise_aka_cluster'
    manifests: 'application-manifest.yaml'